name: CI/CD pipeline with Notifications

on:
  push:
    branches:
      - lab9-KMC
  pull_request:
    branches:
      - lab9-KMC    
  schedule:
    - cron: '0 8 * * 1'  # Exécuter chaque semaine le lundi à 8h

env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Build application
        run: |
          pnpm install
          pnpm build
        if: github.ref == 'refs/heads/lab9-KMC' || github.event_name == 'pull_request' 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: dist/
        if: github.ref == 'refs/heads/lab9-KMC' 
        env:
          ARTIFACT_RETENTION_DAYS: 7

  static-analysis-and-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install
        if: github.event_name == 'pull_request'

      - name: Run static analysis
        run: npm run lint
        if: github.event_name == 'pull_request'

      - name: Run unit tests
        run: npm test
        if: github.event_name == 'pull_request'

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to QA
        if: github.event_name == 'workflow_dispatch'
        run: |
          pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-qa --env=production
        # Nouvelle étape pour envoyer une notification par e-mail en cas d'échec du déploiement
      - name: Notify on deployment failure
        if: failure()
        run: |
          echo "Deployment to QA has failed. Please investigate." | mail -s "Deployment Failure Notification" oussama20benmoussa@gmail.com

  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Prod
        if: github.event_name == 'workflow_dispatch'
        run: |
          pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production  
