name: CI/CD pipeline with Enhanced Features

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1'  # Exécuter chaque semaine le lundi à 8h

env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Build application
        run: |
          pnpm install
          pnpm build
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' 

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: dist/
        if: github.ref == 'refs/heads/main' 
        env:
          ARTIFACT_RETENTION_DAYS: ${{ github.event_name == 'pull_request' ? 1 : 7 }}

  static-analysis-and-tests:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        run_static_and_tests: ["true", "false"]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm install
        if: github.event_name == 'pull_request' && matrix.run_static_and_tests == 'true'

      - name: Run static analysis
        run: npm run lint
        if: github.event_name == 'pull_request' && matrix.run_static_and_tests == 'true'

      - name: Run unit tests
        run: npm test
        if: github.event_name == 'pull_request' && matrix.run_static_and_tests == 'true'

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    inputs:
      run_static_and_tests:
        description: "Whether to run static analysis and tests"
        required: true
        default: "false"
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to QA
        if: github.event_name == 'workflow_dispatch' && inputs.run_static_and_tests == 'true'
        run: |
          pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-qa --env=production
          
  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    inputs:
      run_static_and_tests:
        description: "Whether to run static analysis and tests"
        required: true
        default: "false"
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Prod
        if: github.event_name == 'workflow_dispatch' && inputs.run_static_and_tests == 'true'
        run: |
          pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production
      
  conditional-run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check if files are not in /docs
        if: "!contains(github.event.head_commit.modified, '/docs/')" 
        run: echo "Run pipeline as files are not in /docs"

